import json
import os
import sys
from datetime import datetime
from github import Github, GithubException

# ---------- Config ----------
TOKEN = os.getenv("GITHUB_TOKEN")
REPO_NAME = os.getenv("GITHUB_REPOSITORY")          # auto-set by GitHub Actions
BASE_BRANCH = os.getenv("BASE_BRANCH", "main")
TARGET_FILE = os.getenv("TARGET_FILE", "app/main.py")
AGENT_RESPONSE = "reports/agent_response.json"
DECISION_FILE = "reports/decision.json"

if not TOKEN or not REPO_NAME:
    print("❌ GITHUB_TOKEN or GITHUB_REPOSITORY not set")
    sys.exit(1)

# ---------- Load AI Agent Response ----------
if not os.path.exists(AGENT_RESPONSE):
    print(f"❌ {AGENT_RESPONSE} not found")
    sys.exit(1)

with open(AGENT_RESPONSE) as f:
    agent = json.load(f)

with open(DECISION_FILE) as f:
    decision = json.load(f)

severity = agent.get("severity", "UNKNOWN")
confidence = agent.get("confidence_score", 0)
summary = agent.get("summary", "AI-generated security remediation")
fixed_code = agent.get("fixed_code", "").strip()
recommendations = agent.get("recommendations", [])
auto_fix = decision.get("auto_fix", False)

if not fixed_code:
    print("⚠️  No fixed_code from AI agent — skipping PR")
    sys.exit(0)

# ---------- Connect to GitHub ----------
# Use modern PyGithub auth when available to avoid deprecation warnings.
try:
    # PyGithub >= 2.0 provides Auth and token-based auth via Github(auth=...)
    from github import Auth
    g = Github(auth=Auth.Token(TOKEN))
except Exception:
    # Fall back to older constructor (keeps compatibility with older PyGithub)
    g = Github(TOKEN)

repo = g.get_repo(REPO_NAME)

timestamp = datetime.utcnow().strftime("%Y%m%d-%H%M%S")
branch_name = f"ai-remediation/{severity.lower()}-{timestamp}"

# ---------- Create Branch ----------
base = repo.get_branch(BASE_BRANCH)
try:
    repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base.commit.sha)
    print(f"✅ Branch created: {branch_name}")
except GithubException as e:
    print(f"❌ Branch creation failed: {e}")
    sys.exit(1)

# ---------- Commit Fixed Code ----------
try:
    contents = repo.get_contents(TARGET_FILE, ref=BASE_BRANCH)
    repo.update_file(
        path=TARGET_FILE,
        message=f"fix(security): AI remediation for {severity} severity issue",
        content=fixed_code,
        sha=contents.sha,
        branch=branch_name
    )
    print(f"✅ {TARGET_FILE} updated on {branch_name}")
except GithubException as e:
    print(f"❌ File update failed: {e}")
    sys.exit(1)

# ---------- Build PR Body ----------
recs = "\n".join(f"- {r}" for r in recommendations) or "_None provided_"
auto_merge_note = (
    "🟢 **Auto-merge eligible** — will merge after CI passes."
    if auto_fix else
    "🚨 **Human approval required** — please review before merging."
)

body = f"""## 🤖 AI Security Remediation

{auto_merge_note}

### 📊 Analysis
- **Severity:** `{severity}`
- **Confidence:** `{confidence}%`
- **Auto-fix allowed:** `{auto_fix}`

### 📝 Summary
{summary}

### 🛡️ Recommendations
{recs}

### 🔧 Changed Files
- `{TARGET_FILE}`

---
_Generated by **Agentic Self-Healing CI/CD Pipeline** • {datetime.utcnow().isoformat()}Z_
"""

# ---------- Create PR ----------
try:
    pr = repo.create_pull(
        title=f"[AI-Remediation] {severity} severity fix in {TARGET_FILE}",
        body=body,
        head=branch_name,
        base=BASE_BRANCH
    )
    print(f"✅ PR created: {pr.html_url}")

    # Add labels for triage
    labels = ["ai-remediation", f"severity-{severity.lower()}"]
    if not auto_fix:
        labels.append("needs-human-review")
    try:
        pr.add_to_labels(*labels)
        print(f"🏷️  Labels added: {labels}")
    except GithubException:
        print("⚠️  Could not add labels (labels may not exist in repo)")

except GithubException as e:
    # Provide actionable guidance when GitHub Actions is not allowed to create PRs.
    msg = str(e)
    print(f"❌ PR creation failed: {msg}")

    # Common CI cause: GITHUB_TOKEN permissions or repo/org settings block Actions from creating PRs.
    if 'GitHub Actions is not permitted to create or approve pull requests' in msg or 'is not permitted to create or approve pull requests' in msg:
        print('\nPossible resolutions:')
        print('- Give the workflow `pull-requests: write` and `contents: write` permissions in your workflow YAML:')
        print('  permissions:')
        print('    contents: write')
        print('    pull-requests: write')
        print('\n- Or create a Personal Access Token (classic) or fine-grained token with `repo` scope,')
        print('  store it as a repository secret (e.g. `PAT_TOKEN`) and set the Actions step to use it:')
        print('  env:')
        print('    GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}')
        print('\n- If this repo is in an organization, ensure the organization allows workflows to create PRs (organization settings).')

    sys.exit(1)
